---
- command: sudo /etc/init.d/apache2 stop

- command: sudo apt-get update

- command: sudo apt-get install -y {{ package_name }}

- { include: configure.yml }

- command: sudo /etc/init.d/apache2 start

- command: sudo /bin/su -s /bin/bash www-data -c "php {{ webroot }}/app/console cache:clear --env=prod"

- cron: name="Check Bigbluebutton servers" job="sudo /bin/su -s /bin/bash www-data -c \"php {{ webroot }}/app/console bbblb:servers:check --env=prod\"  > /dev/null 2>&1"
        state=present

- cron: name="Cleanup Bigbluebutton servers" job="sudo /bin/su -s /bin/bash www-data -c \"php {{ webroot }}/app/console bbblb:meetings:cleanup --env=prod\"  > /dev/null 2>&1"
        state=present
